"""Evaluation metrics for Corpus2Skill.

Lexical metrics (F1, BLEU, ROUGE) plus LLM-judge metrics (Factuality, Context Recall).
Prompts follow the WixQA evaluation protocol (arXiv:2505.08643).
"""

from __future__ import annotations

import collections
import json
import re
import time


def _tokenize(text: str) -> list[str]:
    """Simple whitespace + punctuation tokenizer."""
    return re.findall(r"\w+", text.lower())


def compute_f1(prediction: str, reference: str) -> float:
    """Token-level F1 score."""
    pred_tokens = _tokenize(prediction)
    ref_tokens = _tokenize(reference)
    if not pred_tokens or not ref_tokens:
        return 0.0

    pred_counter = collections.Counter(pred_tokens)
    ref_counter = collections.Counter(ref_tokens)
    common = sum((pred_counter & ref_counter).values())

    if common == 0:
        return 0.0
    precision = common / len(pred_tokens)
    recall = common / len(ref_tokens)
    return 2 * precision * recall / (precision + recall)


def compute_bleu(prediction: str, reference: str) -> float:
    """Sentence-level BLEU with smoothing."""
    from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
    pred_tokens = _tokenize(prediction)
    ref_tokens = _tokenize(reference)
    if not pred_tokens or not ref_tokens:
        return 0.0
    smoothing = SmoothingFunction().method1
    return sentence_bleu([ref_tokens], pred_tokens, smoothing_function=smoothing)


def compute_rouge(prediction: str, reference: str) -> dict[str, float]:
    """ROUGE-1 and ROUGE-2 F-measure."""
    from rouge_score import rouge_scorer
    scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2"], use_stemmer=True)
    scores = scorer.score(reference, prediction)
    return {
        "rouge1": scores["rouge1"].fmeasure,
        "rouge2": scores["rouge2"].fmeasure,
    }


# ---------------------------------------------------------------------------
# LLM-judge metrics
# ---------------------------------------------------------------------------

FACTUALITY_PROMPT = """You are a Factual Alignment Expert. Your job is to evaluate how well an AI response includes the essential information from a ground truth answer (GT answer) according to a given user query.

Note that the Ground Truth (GT Answer), is the "Correct" answer generated by an expert, and was created to evaluate the model, and is NOT part of the AI response or the context.

TASK DESCRIPTION:
You will be presented with three elements: a question, a GT answer, and an AI response. Determine how well the AI response includes the essential information from the GT answer that helps to solve the user's query. In case of any additional or extra information present in the AI response, only make sure it's not preventing the user from solving his query.

EVALUATION CRITERIA:
5: Complete Match - All essential information from GT answer appears in AI response, providing complete solution to the query
4: Strong Match - Most essential information is present, with only minor details missing that don't impact the solution significantly
3: Partial Match - Core information is present but missing some important details that would help better solve the query
2: Limited Match - Only basic or partial information present, missing several essential elements needed for the solution
1: Poor Match - Missing most essential information or contains incorrect information that could mislead the user

INSTRUCTIONS:
1. Read the question carefully and analyze the ground truth answer to identify all key information elements that help solve the query
2. Compare the AI response (candidate answer) against the ground truth, focusing on presence of important information
3. Evaluate the completeness and accuracy of the information transfer
4. Assign a rating (1-5) based on how well important information is preserved
5. Provide a brief explanation focusing on factuality

## Question
{question}

## GT Answer
{gold_answer}

## AI Response
{predicted_answer}

Return ONLY a JSON object: {{"score": <1-5 integer>, "explanation": "brief reason"}}"""


CONTEXT_RECALL_PROMPT = """You are a Context Evaluation Expert. Your job is to assess how well a retrieved context contains the essential information present in a ground truth answer (GT answer).

TASK DESCRIPTION:
You will be presented with three pieces of information: a user query, its ground truth answer, and a retrieved context (that will be used to create an AI response from). Determine how well the essential information from the GT answer appears in the retrieved context. Additional information in the retrieved context should not affect the scoring.

EVALUATION CRITERIA:
5: Complete Match - All essential information from the GT answer is present in the retrieved context. The context fully enables answering the user's question.
4: Strong Match - All essential information is present, but some minor details are missing. The context still effectively answers the user's question.
3: Partial Match - Most essential information is present, but some important details are missing. The context partially answers the user's question.
2: Weak Match - Only basic or limited essential information is present. The context provides insufficient information to properly answer the user's question.
1: No Match - Essential information is missing or incorrect. The context cannot be used to answer the user's question.

INSTRUCTIONS:
1. Read the question to understand what the user asks for
2. Break down the GT answer into essential information (key facts, main concepts, direct answers)
3. Check if these information pieces appear in the retrieved context
4. Focus only on finding the ground truth information in the context - ignore extra information
5. Assign a rating (1-5) based on information coverage and relevance

## Question
{question}

## GT Answer
{gold_answer}

## Retrieved Context
{context}

Return ONLY a JSON object: {{"score": <1-5 integer>, "explanation": "brief reason"}}"""


def _llm_judge(prompt: str, client, model: str, max_retries: int = 5) -> dict:
    """Call LLM judge, parse JSON response, normalize score to 0-1."""
    for attempt in range(max_retries + 1):
        try:
            response = client.messages.create(
                model=model,
                max_tokens=300,
                messages=[{"role": "user", "content": prompt}],
            )
            text = response.content[0].text.strip()
            start = text.index("{")
            end = text.rindex("}") + 1
            result = json.loads(text[start:end])
            raw_score = result.get("score", 0)
            return {
                "raw_score": raw_score,
                "score_01": round(raw_score / 5.0, 2),
                "explanation": result.get("explanation", ""),
            }
        except Exception as e:
            if ("429" in str(e) or "rate_limit" in str(e)) and attempt < max_retries:
                delay = 30 * (2 ** attempt)
                time.sleep(delay)
                continue
            return {"raw_score": 0, "score_01": 0.0, "explanation": f"Judge error: {e}"}


def judge_factuality(question: str, predicted: str, gold: str, client, model: str) -> dict:
    """Judge how well the predicted answer captures the gold answer's essential info."""
    prompt = FACTUALITY_PROMPT.format(
        question=question,
        gold_answer=gold[:4000],
        predicted_answer=predicted[:4000],
    )
    return _llm_judge(prompt, client, model)


def judge_context_recall(question: str, gold: str, context: str, client, model: str) -> dict:
    """Judge how well the retrieved context covers the gold answer."""
    prompt = CONTEXT_RECALL_PROMPT.format(
        question=question,
        gold_answer=gold[:4000],
        context=context[:8000],
    )
    return _llm_judge(prompt, client, model)
